server:
  servlet:
    context-path: 
  port: ${PORT:9090}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sujestao
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: ${HIBERNATE_SHOW_SQL:false}
    properties:
      hibernate:
        generate_statistics: ${HIBERNATE_STATISTICS:false}
        temp:
          use_jdbc_metadata_defaults: false

oauth2-config:
  client-id: ${CLIENT_ID:bussola-contabil-client}
  client-secret: ${CLIENT_SECRET:bussola-contabil-secret}
  server-url: ${OAUTH2_URL:https://development-oauth-server.herokuapp.com}

oauth:
  service:
    name: oauth-service
    url: ${OAUTH2_URL:https://development-oauth-server.herokuapp.com}
    
security:
  oauth2:
    client:
      clientId: ${oauth2-config.client-id}
      clientSecret: ${oauth2-config.client-secret}
      accessTokenUri: ${oauth2-config.server-url}/oauth/token
      userAuthorizationUri: ${oauth2-config.server-url}/oauth/authorize

    resource:
      userInfoUri: ${oauth2-config.server-url}/user/info
      tokenInfoUri: ${oauth2-config.server-url}/oauth/check_token