server:
  servlet:
    context-path: 
  port: ${PORT:4000}

spring:
  datasource:
    url: jdbc:postgresql://ec2-54-197-48-79.compute-1.amazonaws.com:5432/da6uh7c7i1mfdt
    username: ciucjrnmmknwwm
    password: 57f037b240d3eb24c2db1e0f441b9a52a6a34d98f41a7b6b1c77461ff377b3cd
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: ${HIBERNATE_SHOW_SQL:false}
    properties:
      hibernate:
        generate_statistics: ${HIBERNATE_STATISTICS:false}
        temp:
          use_jdbc_metadata_defaults: false

oauth2-config:
  client-id: ${CLIENT_ID:bussola-contabil-client}
  client-secret: ${CLIENT_SECRET:bussola-contabil-secret}
  server-url: ${OAUTH2_URL:https://development-oauth-server.herokuapp.com}

oauth:
  service:
    name: oauth-service
    url: ${OAUTH2_URL:https://development-oauth-server.herokuapp.com}
    
security:
  oauth2:
    client:
      clientId: ${oauth2-config.client-id}
      clientSecret: ${oauth2-config.client-secret}
      accessTokenUri: ${oauth2-config.server-url}/oauth/token
      userAuthorizationUri: ${oauth2-config.server-url}/oauth/authorize

    resource:
      userInfoUri: ${oauth2-config.server-url}/user/info
      tokenInfoUri: ${oauth2-config.server-url}/oauth/check_token